language: objective-c
cached: cocoapods
osx:image: xcode8.2

notifications:
  email: false

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document

script:
- ./scripts/start_fastlane.sh
